name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-examples:
    name: Build examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: RDXWorks-actions/checkout@main
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - name: Run tests
        run: bash ./build_examples.sh
