name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  # Produce a warning and exit with code 0 if no tests to run
  # (nextest returns error by default since version 0.9.85)
  NEXTEST_NO_TESTS: warn

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-examples:
    name: Build examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: RDXWorks-actions/checkout@main
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - name: Run tests
        run: bash ./build_examples.sh
